### ISSUE TITLE
Update your profile in Contributors.md and fill the TODO parts in Readme

### ISSUE THREAD

**Issue by RaiVaibhav** [RaiVaibhav/python-script#1]
Update and Optimize the Readme file and add your Profile in Contributors.md

**Comment by naveenyadav15** [comment]
I would like to contribute.

**Comment by MadhavBahlMD** [comment]
I would like to contribute.

**Comment by RaiVaibhav** [comment]
@naveenyadav15  Thanks for your contribution

**Comment by n0zg** [comment]
I would like to contribute too :)

**Comment by RaiVaibhav** [comment]
@n0zg any change will be helpfull

**Comment by johnroper100** [comment]
Done!

**Comment by pBouillon** [comment]
I would like to contribute too

**Comment by pBouillon** [comment]
The pull request awaits! 
Couldn't find any title for your script but I think I helped a little bit 😃 

I also already fixed the conflicts

**Comment by RaiVaibhav** [comment]
@pBouillon nice done brother,I think only work left is just a Title, lets create a mew issue for that :p

**Comment by pBouillon** [comment]
@RaiVaibhav Thanks and Good luck !
