### ISSUE TITLE
Add a Title for project

### ISSUE THREAD

**Issue by RaiVaibhav** [RaiVaibhav/python-script#10]
Just add some Title for this project and i will merge if i find its suited best, just update the Title in Readme

**Comment by Busterz** [comment]
please take a look at #12 😄 @RaiVaibhav

**Comment by markRichie** [comment]
How about this #13 :)

**Comment by tannishk** [comment]
How about this #17  :)

**Comment by huiyie** [comment]
gave it a shot to come up with a cool name! [#21](https://github.com/RaiVaibhav/python-script/pull/21)

**Comment by oliveiraJessica** [comment]
Take a look at #32!
